name: otp_count_down
description: A new dart package for easy implementation of OTP Count Down.
version: 1.0.6
homepage: https://github.com/hiteshgarg002/otp_count_down

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
